### ISSUE TITLE
test namespaces need update

### ISSUE THREAD

**Issue by miner** [juji-io/editscript#1]
`lein test` doesn't work.  The files in test/editscript/diff/* need to have "diff" in their ns declarations.  I guess the files were moved without updating the namespaces.

-(ns editscript.a-star-test
+(ns editscript.diff.a-star-test

-(ns editscript.quick-test
+(ns editscript.diff.quick-test

**Comment by huahaiy** [comment]
Nice catch. Thank you very much! It is now fixed.
