### ISSUE TITLE
MapEntry type crashes diff

### ISSUE THREAD

**Issue by ingesolvoll** [juji-io/editscript#18]
EDIT: This happens in CLJS in the browser.

Case: You use `clojure.core/find` to produce a vector-like structure:

```clj
(def x {:a "a"
        :b "b"})

(find x :a) ;;  => [:a "a"]
;; The above is an instance of `MapEntry`
```

Map entries can mostly be used as a seq. But if you try to diff a structure that includes map entries, editscript will match them as associatives (vectors) and try to kv reduce them. That throws an exception.

**Comment by ingesolvoll** [comment]
Reproduction:

`(editscript.core/diff nil (first {:a :b}))`

**Comment by huahaiy** [comment]
Thanks. I will look into it.

**Comment by huahaiy** [comment]
OK, we can make a MapEntry a :lst instead, that will remove the exception. 

However, keep in mind that we will not be able to recover the MapEtnry type. For example, `(editscript.core/diff nil (first {:a :b}))` => `[[[] :r [:a :b]]]`.

**Comment by lnostdal** [comment]
Is this fix a good idea? If a `MapEntry` on the Clj side is no longer a `MapEntry` (or `cljs.core/MapEnry`) on the Cljs side, can't that break things in surprising and silent(!) ways? It should probably be outside the scope of ES to serialize/deserialize a rich set of data types, but perhaps MapEntry should fail hard as before or be serialized/deserialized proper by ES.

**Comment by lnostdal** [comment]
This seems to work correctly here: https://github.com/lnostdal/editscript/commit/2bc883cd8c24e72c2452010bf1b5deb8fbc39a77

MapEntries are still MapEntries, and there's no exception from kv reduce.

**Comment by huahaiy** [comment]
Good idea. Since the shape of MapEntry is fixed, replacing it as a whole is not going to create a lot of overhead. I will take this idea. Do you mind send a PR?
