### ISSUE TITLE
Unable to resolve symbol: ->EditScript

### ISSUE THREAD

**Issue by miner** [juji-io/editscript#3]
I think the problem is that the ->EditScript function is not defined until after the deftype so it can't be used within the deftype body.  You need to use the inter-op dot notation "EditScript."

Here's what I saw:

$ lein test
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: ->EditScript in this context, compiling:(editscript/edit.cljc:146:5)

My fix is this small diff...

diff --git a/src/editscript/edit.cljc b/src/editscript/edit.cljc
index da9666e..f79b60e 100644
--- a/src/editscript/edit.cljc
+++ b/src/editscript/edit.cljc
@@ -143,7 +143,7 @@
 
   IEditScript
   (combine [this that]
-    (->EditScript (into edits (get-edits that))
+    (EditScript. (into edits (get-edits that))

**Comment by huahaiy** [comment]
Fixed. Thanks.
